package com.tm.hiber.model;
// Generated Jul 16, 2016 8:10:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TaskComments generated by hbm2java
 */
public class TaskComments  implements java.io.Serializable {


     private BigDecimal recordId;
     private BigDecimal refTaskId;
     private String commentText;
     private Date commentDate;

    public TaskComments() {
    }

    public TaskComments(BigDecimal recordId, BigDecimal refTaskId, String commentText, Date commentDate) {
       this.recordId = recordId;
       this.refTaskId = refTaskId;
       this.commentText = commentText;
       this.commentDate = commentDate;
    }
   
    public BigDecimal getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(BigDecimal recordId) {
        this.recordId = recordId;
    }
    public BigDecimal getRefTaskId() {
        return this.refTaskId;
    }
    
    public void setRefTaskId(BigDecimal refTaskId) {
        this.refTaskId = refTaskId;
    }
    public String getCommentText() {
        return this.commentText;
    }
    
    public void setCommentText(String commentText) {
        this.commentText = commentText;
    }
    public Date getCommentDate() {
        return this.commentDate;
    }
    
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }




}


