package com.tm.hiber.model;
// Generated Jul 16, 2016 8:10:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaskPlan generated by hbm2java
 */
public class TaskPlan  implements java.io.Serializable {


     private TaskPlanId id;
     private String analysisLevel;
     private Date plannedDate;
     private String analyst;
     private String auditLastupdateby;
     private Date auditLastupdateon;

    public TaskPlan() {
    }

	
    public TaskPlan(TaskPlanId id, String analysisLevel) {
        this.id = id;
        this.analysisLevel = analysisLevel;
    }
    public TaskPlan(TaskPlanId id, String analysisLevel, Date plannedDate, String analyst, String auditLastupdateby, Date auditLastupdateon) {
       this.id = id;
       this.analysisLevel = analysisLevel;
       this.plannedDate = plannedDate;
       this.analyst = analyst;
       this.auditLastupdateby = auditLastupdateby;
       this.auditLastupdateon = auditLastupdateon;
    }
   
    public TaskPlanId getId() {
        return this.id;
    }
    
    public void setId(TaskPlanId id) {
        this.id = id;
    }
    public String getAnalysisLevel() {
        return this.analysisLevel;
    }
    
    public void setAnalysisLevel(String analysisLevel) {
        this.analysisLevel = analysisLevel;
    }
    public Date getPlannedDate() {
        return this.plannedDate;
    }
    
    public void setPlannedDate(Date plannedDate) {
        this.plannedDate = plannedDate;
    }
    public String getAnalyst() {
        return this.analyst;
    }
    
    public void setAnalyst(String analyst) {
        this.analyst = analyst;
    }
    public String getAuditLastupdateby() {
        return this.auditLastupdateby;
    }
    
    public void setAuditLastupdateby(String auditLastupdateby) {
        this.auditLastupdateby = auditLastupdateby;
    }
    public Date getAuditLastupdateon() {
        return this.auditLastupdateon;
    }
    
    public void setAuditLastupdateon(Date auditLastupdateon) {
        this.auditLastupdateon = auditLastupdateon;
    }




}


