package com.tm.hiber.model;
// Generated Jul 16, 2016 8:10:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TaskOptions generated by hbm2java
 */
public class TaskOptions  implements java.io.Serializable {


     private BigDecimal recordId;
     private String tag;
     private String keyText;
     private String valueText;
     private String description;

    public TaskOptions() {
    }

	
    public TaskOptions(BigDecimal recordId) {
        this.recordId = recordId;
    }
    public TaskOptions(BigDecimal recordId, String tag, String keyText, String valueText, String description) {
       this.recordId = recordId;
       this.tag = tag;
       this.keyText = keyText;
       this.valueText = valueText;
       this.description = description;
    }
   
    public BigDecimal getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(BigDecimal recordId) {
        this.recordId = recordId;
    }
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }
    public String getKeyText() {
        return this.keyText;
    }
    
    public void setKeyText(String keyText) {
        this.keyText = keyText;
    }
    public String getValueText() {
        return this.valueText;
    }
    
    public void setValueText(String valueText) {
        this.valueText = valueText;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


