package com.tm.hiber.model;
// Generated Jul 16, 2016 8:10:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TaskPlanId generated by hbm2java
 */
public class TaskPlanId  implements java.io.Serializable {


     private BigDecimal recordId;
     private BigDecimal refTaskId;

    public TaskPlanId() {
    }

    public TaskPlanId(BigDecimal recordId, BigDecimal refTaskId) {
       this.recordId = recordId;
       this.refTaskId = refTaskId;
    }
   
    public BigDecimal getRecordId() {
        return this.recordId;
    }
    
    public void setRecordId(BigDecimal recordId) {
        this.recordId = recordId;
    }
    public BigDecimal getRefTaskId() {
        return this.refTaskId;
    }
    
    public void setRefTaskId(BigDecimal refTaskId) {
        this.refTaskId = refTaskId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TaskPlanId) ) return false;
		 TaskPlanId castOther = ( TaskPlanId ) other; 
         
		 return ( (this.getRecordId()==castOther.getRecordId()) || ( this.getRecordId()!=null && castOther.getRecordId()!=null && this.getRecordId().equals(castOther.getRecordId()) ) )
 && ( (this.getRefTaskId()==castOther.getRefTaskId()) || ( this.getRefTaskId()!=null && castOther.getRefTaskId()!=null && this.getRefTaskId().equals(castOther.getRefTaskId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRecordId() == null ? 0 : this.getRecordId().hashCode() );
         result = 37 * result + ( getRefTaskId() == null ? 0 : this.getRefTaskId().hashCode() );
         return result;
   }   


}


