package com.tm.hiber.model;
// Generated Jul 16, 2016 8:10:45 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TaskMaster generated by hbm2java
 */
public class TaskMaster  implements java.io.Serializable {


     private BigDecimal taskId;
     private String taskReference;
     private String title;
     private String description;
     private Date createDate;
     private String createdBy;
     private String assignee;
     private String status;
     private Date eta;
     private String projectName;
     private String priority;
     private String commentText;
     private String moduleName;
     private String assumption;
     private String taskType;
     private String auditSysname;
     private String auditLastupdateby;
     private Date auditLastupdateon;
     private String codeRevision;
     private String retrofitRequired;
     private String frameworkVersion;
     private String releasePhase;
     private String releaseNotes;

    public TaskMaster() {
    }

	
    public TaskMaster(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public TaskMaster(BigDecimal taskId, String taskReference, String title, String description, Date createDate, String createdBy, String assignee, String status, Date eta, String projectName, String priority, String commentText, String moduleName, String assumption, String taskType, String auditSysname, String auditLastupdateby, Date auditLastupdateon, String codeRevision, String retrofitRequired, String frameworkVersion, String releasePhase, String releaseNotes) {
       this.taskId = taskId;
       this.taskReference = taskReference;
       this.title = title;
       this.description = description;
       this.createDate = createDate;
       this.createdBy = createdBy;
       this.assignee = assignee;
       this.status = status;
       this.eta = eta;
       this.projectName = projectName;
       this.priority = priority;
       this.commentText = commentText;
       this.moduleName = moduleName;
       this.assumption = assumption;
       this.taskType = taskType;
       this.auditSysname = auditSysname;
       this.auditLastupdateby = auditLastupdateby;
       this.auditLastupdateon = auditLastupdateon;
       this.codeRevision = codeRevision;
       this.retrofitRequired = retrofitRequired;
       this.frameworkVersion = frameworkVersion;
       this.releasePhase = releasePhase;
       this.releaseNotes = releaseNotes;
    }
   
    public BigDecimal getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(BigDecimal taskId) {
        this.taskId = taskId;
    }
    public String getTaskReference() {
        return this.taskReference;
    }
    
    public void setTaskReference(String taskReference) {
        this.taskReference = taskReference;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getAssignee() {
        return this.assignee;
    }
    
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getEta() {
        return this.eta;
    }
    
    public void setEta(Date eta) {
        this.eta = eta;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getPriority() {
        return this.priority;
    }
    
    public void setPriority(String priority) {
        this.priority = priority;
    }
    public String getCommentText() {
        return this.commentText;
    }
    
    public void setCommentText(String commentText) {
        this.commentText = commentText;
    }
    public String getModuleName() {
        return this.moduleName;
    }
    
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }
    public String getAssumption() {
        return this.assumption;
    }
    
    public void setAssumption(String assumption) {
        this.assumption = assumption;
    }
    public String getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(String taskType) {
        this.taskType = taskType;
    }
    public String getAuditSysname() {
        return this.auditSysname;
    }
    
    public void setAuditSysname(String auditSysname) {
        this.auditSysname = auditSysname;
    }
    public String getAuditLastupdateby() {
        return this.auditLastupdateby;
    }
    
    public void setAuditLastupdateby(String auditLastupdateby) {
        this.auditLastupdateby = auditLastupdateby;
    }
    public Date getAuditLastupdateon() {
        return this.auditLastupdateon;
    }
    
    public void setAuditLastupdateon(Date auditLastupdateon) {
        this.auditLastupdateon = auditLastupdateon;
    }
    public String getCodeRevision() {
        return this.codeRevision;
    }
    
    public void setCodeRevision(String codeRevision) {
        this.codeRevision = codeRevision;
    }
    public String getRetrofitRequired() {
        return this.retrofitRequired;
    }
    
    public void setRetrofitRequired(String retrofitRequired) {
        this.retrofitRequired = retrofitRequired;
    }
    public String getFrameworkVersion() {
        return this.frameworkVersion;
    }
    
    public void setFrameworkVersion(String frameworkVersion) {
        this.frameworkVersion = frameworkVersion;
    }
    public String getReleasePhase() {
        return this.releasePhase;
    }
    
    public void setReleasePhase(String releasePhase) {
        this.releasePhase = releasePhase;
    }
    public String getReleaseNotes() {
        return this.releaseNotes;
    }
    
    public void setReleaseNotes(String releaseNotes) {
        this.releaseNotes = releaseNotes;
    }




}


